@apiUrl = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE3NjczOTQ4NjgsImV4cCI6MTc2NzM5NDkyOCwidHlwIjoiYWNjZXNzIn0.42V73Pgq4siKqMMj3KWWVllQppVGClO7IeG4R8_wJNU

###

# @name list

GET {{apiUrl}}/albums
Authorization: Bearer {{token}}

###

# @name retrieve

GET {{apiUrl}}/albums/1
Authorization: Bearer {{token}}
