/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as appIndexRouteImport } from './routes/(app)/index'
import { Route as appTracksIndexRouteImport } from './routes/(app)/tracks/index'
import { Route as appTasksIndexRouteImport } from './routes/(app)/tasks/index'
import { Route as appSettingsIndexRouteImport } from './routes/(app)/settings/index'
import { Route as appNotifiersIndexRouteImport } from './routes/(app)/notifiers/index'
import { Route as appJobsIndexRouteImport } from './routes/(app)/jobs/index'
import { Route as appArtistsIndexRouteImport } from './routes/(app)/artists/index'
import { Route as appAlbumsIndexRouteImport } from './routes/(app)/albums/index'
import { Route as appArtistsIdRouteImport } from './routes/(app)/artists/$id'

const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const appIndexRoute = appIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appRouteRoute,
} as any)
const appTracksIndexRoute = appTracksIndexRouteImport.update({
  id: '/tracks/',
  path: '/tracks/',
  getParentRoute: () => appRouteRoute,
} as any)
const appTasksIndexRoute = appTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => appRouteRoute,
} as any)
const appSettingsIndexRoute = appSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => appRouteRoute,
} as any)
const appNotifiersIndexRoute = appNotifiersIndexRouteImport.update({
  id: '/notifiers/',
  path: '/notifiers/',
  getParentRoute: () => appRouteRoute,
} as any)
const appJobsIndexRoute = appJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => appRouteRoute,
} as any)
const appArtistsIndexRoute = appArtistsIndexRouteImport.update({
  id: '/artists/',
  path: '/artists/',
  getParentRoute: () => appRouteRoute,
} as any)
const appAlbumsIndexRoute = appAlbumsIndexRouteImport.update({
  id: '/albums/',
  path: '/albums/',
  getParentRoute: () => appRouteRoute,
} as any)
const appArtistsIdRoute = appArtistsIdRouteImport.update({
  id: '/artists/$id',
  path: '/artists/$id',
  getParentRoute: () => appRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof appIndexRoute
  '/login': typeof LoginIndexRoute
  '/artists/$id': typeof appArtistsIdRoute
  '/albums': typeof appAlbumsIndexRoute
  '/artists': typeof appArtistsIndexRoute
  '/jobs': typeof appJobsIndexRoute
  '/notifiers': typeof appNotifiersIndexRoute
  '/settings': typeof appSettingsIndexRoute
  '/tasks': typeof appTasksIndexRoute
  '/tracks': typeof appTracksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof appIndexRoute
  '/login': typeof LoginIndexRoute
  '/artists/$id': typeof appArtistsIdRoute
  '/albums': typeof appAlbumsIndexRoute
  '/artists': typeof appArtistsIndexRoute
  '/jobs': typeof appJobsIndexRoute
  '/notifiers': typeof appNotifiersIndexRoute
  '/settings': typeof appSettingsIndexRoute
  '/tasks': typeof appTasksIndexRoute
  '/tracks': typeof appTracksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)': typeof appRouteRouteWithChildren
  '/(app)/': typeof appIndexRoute
  '/login/': typeof LoginIndexRoute
  '/(app)/artists/$id': typeof appArtistsIdRoute
  '/(app)/albums/': typeof appAlbumsIndexRoute
  '/(app)/artists/': typeof appArtistsIndexRoute
  '/(app)/jobs/': typeof appJobsIndexRoute
  '/(app)/notifiers/': typeof appNotifiersIndexRoute
  '/(app)/settings/': typeof appSettingsIndexRoute
  '/(app)/tasks/': typeof appTasksIndexRoute
  '/(app)/tracks/': typeof appTracksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/artists/$id'
    | '/albums'
    | '/artists'
    | '/jobs'
    | '/notifiers'
    | '/settings'
    | '/tasks'
    | '/tracks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/artists/$id'
    | '/albums'
    | '/artists'
    | '/jobs'
    | '/notifiers'
    | '/settings'
    | '/tasks'
    | '/tracks'
  id:
    | '__root__'
    | '/(app)'
    | '/(app)/'
    | '/login/'
    | '/(app)/artists/$id'
    | '/(app)/albums/'
    | '/(app)/artists/'
    | '/(app)/jobs/'
    | '/(app)/notifiers/'
    | '/(app)/settings/'
    | '/(app)/tasks/'
    | '/(app)/tracks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appRouteRoute: typeof appRouteRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/': {
      id: '/(app)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/tracks/': {
      id: '/(app)/tracks/'
      path: '/tracks'
      fullPath: '/tracks'
      preLoaderRoute: typeof appTracksIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/tasks/': {
      id: '/(app)/tasks/'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof appTasksIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/settings/': {
      id: '/(app)/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof appSettingsIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/notifiers/': {
      id: '/(app)/notifiers/'
      path: '/notifiers'
      fullPath: '/notifiers'
      preLoaderRoute: typeof appNotifiersIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/jobs/': {
      id: '/(app)/jobs/'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof appJobsIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/artists/': {
      id: '/(app)/artists/'
      path: '/artists'
      fullPath: '/artists'
      preLoaderRoute: typeof appArtistsIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/albums/': {
      id: '/(app)/albums/'
      path: '/albums'
      fullPath: '/albums'
      preLoaderRoute: typeof appAlbumsIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/artists/$id': {
      id: '/(app)/artists/$id'
      path: '/artists/$id'
      fullPath: '/artists/$id'
      preLoaderRoute: typeof appArtistsIdRouteImport
      parentRoute: typeof appRouteRoute
    }
  }
}

interface appRouteRouteChildren {
  appIndexRoute: typeof appIndexRoute
  appArtistsIdRoute: typeof appArtistsIdRoute
  appAlbumsIndexRoute: typeof appAlbumsIndexRoute
  appArtistsIndexRoute: typeof appArtistsIndexRoute
  appJobsIndexRoute: typeof appJobsIndexRoute
  appNotifiersIndexRoute: typeof appNotifiersIndexRoute
  appSettingsIndexRoute: typeof appSettingsIndexRoute
  appTasksIndexRoute: typeof appTasksIndexRoute
  appTracksIndexRoute: typeof appTracksIndexRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appIndexRoute: appIndexRoute,
  appArtistsIdRoute: appArtistsIdRoute,
  appAlbumsIndexRoute: appAlbumsIndexRoute,
  appArtistsIndexRoute: appArtistsIndexRoute,
  appJobsIndexRoute: appJobsIndexRoute,
  appNotifiersIndexRoute: appNotifiersIndexRoute,
  appSettingsIndexRoute: appSettingsIndexRoute,
  appTasksIndexRoute: appTasksIndexRoute,
  appTracksIndexRoute: appTracksIndexRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appRouteRoute: appRouteRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
